services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    environment:
      - CHROMA_DATABASE_DIR=/data
    volumes:
      - ./chroma_db:/data
  streamlit:
    image: streamlit:latest
    container_name: app_app
    depends_on:
      - chromadb
    build:
      context: .
    ports:
      - "8502:8501"
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    volumes:
      # - ./:/app
      - ./.env:/app/.env